name: Update Tacklets JSON

on:
  push:
    paths:
      - 'tacklets/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-tacklets-json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Create directory if it doesn't exist
        run: mkdir -p directory
      
      - name: Update tacklets.json
        run: |
          node .github/scripts/update-tacklets.js
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add directory/tacklets.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update tacklets.json"
          git push
